name: Push server to Heroku

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    paths:
    - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Release server
      uses: akhileshns/heroku-deploy@v3.12.12
      with: 
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "codehort-server"
        heroku_email: ${{secrets.HEROKU_API_KEY}}
        buildpack: "https://github.com/lstoll/heroku-buildpack-monorepo.git"
        appdir: server
      env:
        HD_APP_BASE: "codehort/server"
